repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args: [--line-length=88]


  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.292
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --ignore=F841, --line-length=88]


  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.10  # or any later Vulture version
    hooks:
      - id: vulture
        args:
          - --min-confidence=100
          - ai/tilly